name: lint

on: [ "push", "pull_request" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run gofmt
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/gofmt.sh"
          "${GITHUB_WORKSPACE}/.github/gofmt.sh"

      - name: Run golint
        run: golint -set_exit_status ./...